### PR TITLE
Use more powerful IAM capability for CF updates

### PR DESCRIPTION
**Pull request by adamnfish**
CAPABILITY_NAMED_IAM is a strictly more powerful than CAPABILITY_IAM. That extra power is something we need occasionally but it is fine to always pass it.

### CODE REVIEW

**Comment by johnduffell** [comment]
ok, but CAPABILITY_IAM = CAPABILITY_NAMED_IAM?
consider rename the variable too?

**Comment by adamnfish** [comment]
Yeah, would be better that way. I'll have to open it in IntelliJ to do ti that way which takes a bit longer is all.

**Comment by adamnfish** [comment]
@johnduffell fixed, thanks

**Comment by johnduffell** [comment]
💥 🚀 any time 😉 👍

**Comment by sihil** [comment]
@adamnfish Should this be merged and pushed out?

**Comment by adamnfish** [comment]
Almost certainly!

I lack the access and skills to do so though. Happy to work with someone that knows Riff Raff to do this, but it probably won't be before the GDPR deadline for me.

**Pull request merged**
