### PR TITLE
Replace the spinner with the party parrot (this won't be annoying)

### PR DESCRIPTION
**Pull request by sihil**

### CODE REVIEW

**Comment by susiecoleman** [comment]
👍 
Excellent feature

**Comment by cb372** [comment]
Argh! Merge conflict! Stop touching Riff Raff!

**Comment by sihil** [comment]
Sorry! It was tiny! I'll stop now. Promise. Honest. 😶

**Comment by jennysivapalan** [comment]
I'm enjoying the parrots. The conflict was worth it.

**Comment by katebee** [comment]
This is ...fantastic 😂

**Pull request merged**
