### PR TITLE
Some documentation for when riffraff needs to be moved between hosts.

### PR DESCRIPTION
**Pull request by AWare**
@philwills  Some docs about this mornings host swap for you.

Also: what do we think about changing output of `management/switchboard` to plain text to make it easier to parse curl output?

### CODE REVIEW

**Comment by philwills** [comment]
Looks good to me. I'm sure @sihil will have some input when he gets back, but I think merging this is an improvement over where we are now.

**Comment by sihil** [comment]
Thanks @AWare.

My normal (aka lazy) approach is to check there are no deploys running and then terminate the existing instance (then check it recovers). This approach is probably safer, but it will act weirdly (if your deploy request hits one backend then it will be able to start but if it hits the other it will not).

Happy for this to be merged though as it's not dangerous, just potentially confusing for users.

**Comment by AWare** [comment]
@sihil It shouldn't, the new box isn't joined to the ELB until it's had deploys blocked. And then they're not unblocked until the old one is gone.

**Comment by sihil** [comment]
You're quite right, my bad.

**Pull request merged**
