### PR TITLE
Fail the deploy fast when zero s3 artefacts are uploaded

### PR DESCRIPTION
**Pull request by katebee**
Fix for https://github.com/guardian/riff-raff/issues/482

### CODE REVIEW

**Comment by AWare** [comment]
We appropriately vandalised a build: https://riffraff.code.dev-gutools.co.uk/deployment/view/73783f37-cb50-46e8-ab50-6cf41f1f0f43

**Comment by AWare** [comment]
@sihil is there a valid reason for a build to attempt to upload 0 artefacts?

**Comment by sihil** [comment]
If that would imply that it failed to even upload a `riff-raff.yaml` then absolutely not.

If that were to exempt a `riff-raff.yaml` I suspect it would still make no sense although there might be an exemption to that rule that I can't think of.

**Comment by sihil** [comment]
I realised I was assuming that this was to do with sbt-riffraff-artifact failing the build. Actually we mean failing the deploy here and I've updated the title of the PR to reflect this.

**Pull request merged**
