### PR TITLE
Fix relative links in index.md

### PR DESCRIPTION
**Pull request by thomaska**
The relative links in the `index.md` files don't have the suffix `.md` and return a 404.
Eg.:
screen shot 2016-11-14 at 15 43 19

This is an attempt to repair the broken links.
cc @sihil

### CODE REVIEW

**Comment by philwills** [comment]
These are intended for viewing in the app, e.g. https://host/docs/magenta-lib/concepts/, rather than via Github and by that point, they don't need the `.md` extension. If we wanted to support links in Github we'd need to at least change the rendering app as well to support the `.md` extension.

**Comment by sihil** [comment]
I suspect (but haven't checked) that this will break the documentation links when used inside riff-raff (https://riffraff.gutools.co.uk/docs/). Can you maybe deploy to CODE and confirm how the parser handles this? It might be that adding a new route that chops off the .md automatically would fix this for both github and internal browsing.

**Comment by thomaska** [comment]
Oh ok. This makes sense then! Sorry I wasn't aware of the https://riffraff.gutools.co.uk/docs/ !
@sihil I tried deploying on CODE but I got:
`
[13:35:22] task ChangeSwitch shutdown-when-inactive to ON
[13:37:29] Unhandled exception in task ChangeSwitch shutdown-when-inactive to ON`

Is it ok if I just close this PR?

**Comment by sihil** [comment]
Did you deploy from the CODE instance of Riff-Raff? At the moment you cannot cross deploy from PROD to CODE or CODE to PROD.

You're the second person to try doing this and I think it's a quick fix to make it work in both contexts so I'd advocate doing that.

**Comment by thomaska** [comment]
@sihil Thanks for passing by today! 
I deployed on CODE and checked the github links and both seem ok now.

**Comment by sihil** [comment]
Looks great. 👍

**Pull request merged**
