### PR TITLE
Use the "table-name-$STAGE" convention for Dynamo table names

### PR DESCRIPTION
**Pull request by cb372**
Look up the stage using the instance's tags.

@sihil @philwills

### CODE REVIEW

**Comment by sihil** [comment]
LGTM 👍

**Comment by cb372** [comment]
I've migrated the CD configs to the new Dynamo table, and checked that the stage lookup code works in CODE.

**Comment by philwills** [comment]
This is good, but I wonder whether for local work we want to use DynamoDB local, rather than DEV tables.

**Comment by cb372** [comment]
Good point. I was going to add an "if stage == DEV then use CODE" fudge when calculating the table name, but I forgot. I'm happy either doing that or using Dynamo local.

**Comment by sihil** [comment]
Ooo DynamoDB local is in maven. That's a cute way to actually test things.

**Comment by cb372** [comment]
For now I've added code to my Play 2.5 branch to use the CODE tables when running on developer machines. We can switch to Dynamo local later if necessary.

**Comment by philwills** [comment]
Sounds reasonable. 

@sihil for the purpose of tests, as opposed to spinning things up to look at locally, I'd argue for https://github.com/localytics/sbt-dynamodb

**Pull request merged**
